spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webflux-clustercourse.dll9j9r.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&appName=webflux-clustercourse
      auto-index-creation: true
  application:
    name: webflux-course